include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    require_trailing_commas: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_unnecessary_containers: true
    prefer_final_locals: true
    prefer_final_in_for_each: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
