[build]
  command= "flutter pub get && flutter pub run sqflite_common_ffi_web:setup && flutter build web --release"
  base    = "."
  publish = "build/web"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
